"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="clean_text"."""


def make_clean_text():
    inputs = {
        'input_text': 'What is the capital of France and what is the current population of Paris?',
        'check_mode': 'validate',
    }
    return inputs, 'clean_text', 'Benign user query — no threat patterns, returns clean=True severity=clean action=allow with zero findings'
