"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="safe_allowlisted_url"."""


def make_safe_allowlisted_url():
    inputs = {
        'input_text': 'https://api.github.com/repos/anthropics/anthropic-sdk-python/releases/latest',
        'check_mode': 'check_url',
    }
    return inputs, 'safe_allowlisted_url', 'URL on the ALLOWED_DOMAINS allowlist — github.com passes cleanly, action=allow with no SSRF findings'
