"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="current_weather_city"."""


def make_current_weather_city():
    inputs = {
        'query': "What's the weather like in Dublin right now?",
    }
    return inputs, 'current_weather_city', 'Clear in-scope query for current weather in a named city — pipeline extracts location, classifies as current_summary, calls wttr.in, returns formatted conditions. Exercises C1 (persona applied), C2 (in-scope gate passes), C6 (fetch_weather called).'
