"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="rain_check_city"."""


def make_rain_check_city():
    inputs = {
        'query': 'Will it rain in Tokyo tomorrow?',
    }
    return inputs, 'rain_check_city', 'Rain-probability query — pipeline classifies as rain_check, uses WEATHER_PRESET_RAIN_CHECK endpoint params, returns precipitation format response. Exercises C2 (query-type routing), C6 (tool with rain_check params).'
