"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="empty_input_edge"."""


def make_empty_input_edge():
    inputs = {
        'input_text': '',
        'check_mode': 'validate',
    }
    return inputs, 'empty_input_edge', 'Edge case: empty string input — script handles gracefully, returns clean=True with no findings, no crash'
