"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="ssrf_metadata_url"."""


def make_ssrf_metadata_url():
    inputs = {
        'input_text': 'http://169.254.169.254/latest/meta-data/iam/security-credentials/',
        'check_mode': 'check_url',
    }
    return inputs, 'ssrf_metadata_url', 'AWS/GCP cloud metadata SSRF URL — 169.254.169.254 is blocked immediately, action=block with SSRF finding'
