"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="clean_secure_parameterized"."""


def make_clean_secure_parameterized():
    inputs = {
        'diff': """diff --git a/api/payments.py b/api/payments.py
new file mode 100644
index 0000000..c4d5e6f
--- /dev/null
+++ b/api/payments.py
@@ -0,0 +1,35 @@
+from django.http import JsonResponse
+from django.contrib.auth.decorators import login_required
+from django.views.decorators.http import require_POST
+from django.core.validators import MinValueValidator
+from decimal import Decimal
+from .models import Payment
+
+@login_required
+def get_my_payments(request):
+    payments = Payment.objects.filter(
+        user=request.user
+    ).values('id', 'amount', 'status', 'created_at').order_by('-created_at')[:50]
+    return JsonResponse({'payments': list(payments)})
+
+@login_required
+@require_POST
+def create_payment(request):
+    import json
+    try:
+        body = json.loads(request.body)
+    except json.JSONDecodeError:
+        return JsonResponse({'error': 'invalid json'}, status=400)
+    amount = body.get('amount')
+    try:
+        amount = Decimal(str(amount))
+        if amount <= 0:
+            raise ValueError
+    except (TypeError, ValueError):
+        return JsonResponse({'error': 'invalid amount'}, status=400)
+    payment = Payment.objects.create(
+        user=request.user,
+        amount=amount,
+        status='pending',
+    )
+    return JsonResponse({'payment_id': payment.id, 'status': payment.status}, status=201)""",
    }
    return inputs, 'clean_secure_parameterized', 'Diff adds a payment endpoint with parameterized queries, proper ownership checks, and input validation — should find no issues'
