"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="edge_empty_diff"."""


def make_edge_empty_diff():
    inputs = {
        'diff': '',
    }
    return inputs, 'edge_empty_diff', 'Empty diff string — pipeline should return an empty FindingsReport with no issues and note that no modified files were found'
