"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="airport_code_lookup"."""


def make_airport_code_lookup():
    inputs = {
        'query': 'What is the weather at ORD?',
    }
    return inputs, 'airport_code_lookup', "IATA airport code location — pipeline extracts 'ORD' as location identifier and resolves via wttr.in airport code support, returning weather at Chicago O'Hare. Exercises C8 (airport code feature), C6 (tool call with airport code)."
