"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="detailed_conditions_city"."""


def make_detailed_conditions_city():
    inputs = {
        'query': 'Show me detailed current conditions in Paris including wind and humidity',
    }
    return inputs, 'detailed_conditions_city', 'Explicit request for detailed current conditions — pipeline classifies as current_detailed, uses WEATHER_PRESET_FULL_CONDITIONS format string returning temperature, feels-like, wind, and humidity. Exercises C6 (full conditions preset), C2 (detail-level routing).'
