"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="out_of_scope_historical"."""


def make_out_of_scope_historical():
    inputs = {
        'query': 'What was the weather in London during the Great Storm of 1987?',
    }
    return inputs, 'out_of_scope_historical', 'Historical weather request — pipeline classifies as out_of_scope (historical data is explicitly out-of-scope), returns graceful refusal without calling wttr.in. Exercises C2 (out-of-scope gate fires), C1 (persona-appropriate refusal message).'
