"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="query_no_location"."""


def make_query_no_location():
    inputs = {
        'query': 'What is the weather?',
    }
    return inputs, 'query_no_location', 'Query with no location specified — pipeline extracts empty/null location, classifies as current_summary, falls back to IP-based geolocation via wttr.in (empty location string). Exercises C1 (graceful no-location handling), C2 (in-scope, passes gate).'
