"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="week_forecast"."""


def make_week_forecast():
    inputs = {
        'query': 'Give me the week-long forecast for New York City',
    }
    return inputs, 'week_forecast', 'Weekly forecast request — pipeline classifies as forecast_week, uses WEATHER_PRESET_WEEK_FORECAST params (v2 format). Exercises C6 (forecast preset), C2 (multi-day routing).'
