"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="architectural_issue_detected"."""


def make_architectural_issue_detected():
    inputs = {
        'issue_description': 'Race condition in distributed job queue: workers intermittently process the same job twice, causing duplicate email sends and double-charges. Occurs under load with 4+ workers.',
        'error_text': """ERROR duplicate_job_processor: Job job_id=7823 already processed by worker-2, now processing on worker-4
ERROR payment_service: Duplicate charge detected for order_id=4421
WARNING email_service: Duplicate welcome email sent to user_id=9912""",
        'recent_changes': 'Fix attempt 1: Added Redis SETNX lock with 30s TTL — resolved for low load but deadlock under high concurrency when lock expires before job completes. Fix attempt 2: Changed to optimistic locking in PostgreSQL (version field) — fixed the lock issue but revealed that job_status updates across the queue/worker boundary are not atomic. Fix attempt 3: Added deduplication table with job_id unique constraint — resolved atomicity but revealed that worker heartbeat resets allow zombie workers to reclaim in-progress jobs.',
        'code_context': """class JobQueue:
    def claim_next_job(self, worker_id: str) -> Optional[Job]:
        job = self.db.query('SELECT * FROM jobs WHERE status=? LIMIT 1', 'pending')
        if job:
            self.db.execute('UPDATE jobs SET status=?, worker_id=? WHERE id=?',
                          'processing', worker_id, job.id)
        return job  # Multiple workers can claim same job between SELECT and UPDATE""",
        'working_examples_text': '',
        'fix_attempts_count': 3,
    }
    return inputs, 'architectural_issue_detected', 'Architectural threshold case (C8 MAX_FIX_ATTEMPTS=3): distributed job queue has race condition where workers process the same job twice — 3 fix attempts each revealed new coupling problems — pipeline should detect architectural_problem pattern and recommend team discussion instead of another fix'
