"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="test_failure_after_refactor"."""


def make_test_failure_after_refactor():
    inputs = {
        'issue_description': "All 12 authentication tests fail after yesterday's session middleware refactor — returning 401 Unauthorized on valid credentials",
        'error_text': """FAILED tests/test_auth.py::test_login_valid_credentials - AssertionError: assert 401 == 200
FAILED tests/test_auth.py::test_login_remember_me - AssertionError: assert 401 == 200
FAILED tests/test_auth.py::test_session_persistence - AssertionError: assert 401 == 200

All failures are 401 responses where 200 is expected. Tests were passing before the refactor.""",
        'recent_changes': 'Refactored SessionMiddleware: replaced cookie-based sessions with JWT tokens. Changed __call__ method to decode Authorization header instead of reading session cookie. Removed set_cookie() calls from login handler. Updated User.from_session() to User.from_jwt_token().',
        'code_context': """class SessionMiddleware:
    def __call__(self, environ, start_response):
        token = environ.get('HTTP_AUTHORIZATION', '').removeprefix('Bearer ')
        if token:
            user = User.from_jwt_token(token)  # May raise if token format unexpected
            environ['user'] = user
        return self.app(environ, start_response)

def login(request):
    user = authenticate(request.POST['username'], request.POST['password'])
    if user:
        token = generate_jwt(user)
        return JsonResponse({'token': token})  # Tests may still be sending cookie header""",
        'working_examples_text': '',
        'fix_attempts_count': 0,
    }
    return inputs, 'test_failure_after_refactor', 'Positive case with recent changes: all authentication tests fail after session middleware refactor — pipeline should trace root cause to JWT migration and identify missing token validation (exercises C1, C2, C8 BACKEND/MODEL_ID)'
