"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="intermittent_import_failure"."""


def make_intermittent_import_failure():
    inputs = {
        'issue_description': "CI pipeline randomly fails with ModuleNotFoundError on 'pytest' approximately 3 times per week. Always passes on manual retry with no changes. Affects all branches, not correlated with any specific commit.",
        'error_text': """ModuleNotFoundError: No module named 'pytest'
  File '/home/runner/work/myapp/myapp/run_tests.sh', line 4, in <module>
    python -m pytest tests/

pip install exit code: 0
pip show pytest: WARNING: Package(s) not found: pytest

Note: requirements.txt contains pytest==7.4.0. Installation log shows success but package not found.""",
        'recent_changes': '',
        'code_context': '',
        'working_examples_text': '',
        'fix_attempts_count': 0,
    }
    return inputs, 'intermittent_import_failure', 'Intermittent/environmental case: CI pipeline randomly fails on module import roughly 3 times per week but always passes on retry — pipeline should determine reproducibility is intermittent and guide evidence gathering rather than proposing immediate fixes (exercises C1, C2 anti-premature-fix requirements)'
