"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="minimal_description_only"."""


def make_minimal_description_only():
    inputs = {
        'issue_description': 'Application crashes on startup with exit code 1 in production but not in staging',
        'error_text': '',
        'recent_changes': '',
        'code_context': '',
        'working_examples_text': '',
        'fix_attempts_count': 0,
    }
    return inputs, 'minimal_description_only', 'Edge case: minimal input with only issue_description and no supporting context — pipeline should still run all phases and produce a report with honest uncertainty acknowledgment and evidence-gathering next steps, not premature fix proposals (exercises C1, C2 epistemic honesty requirement)'
