"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="simple_type_error"."""


def make_simple_type_error():
    inputs = {
        'issue_description': "Function 'process_user_data' raises TypeError at line 47 when handling requests with optional age field",
        'error_text': """TypeError: '<' not supported between instances of 'NoneType' and 'int'
  File 'app/processors.py', line 47, in process_user_data
    if user.age < 18:
  File 'app/api.py', line 23, in handle_request
    result = process_user_data(request.body)
  File 'app/wsgi.py', line 8, in application
    return handle_request(environ, start_response)""",
        'recent_changes': '',
        'code_context': """def process_user_data(user):
    # user.age may be None for anonymous users
    if user.age < 18:
        return restricted_response(user)
    return full_response(user)""",
        'working_examples_text': '',
        'fix_attempts_count': 0,
    }
    return inputs, 'simple_type_error', 'Positive case: clear TypeError with stack trace — pipeline should identify NoneType comparison as root cause and produce a complete Phase 1-4 report (exercises C1 persona, C2 Iron Law requirements)'
