"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="working_example_comparison"."""


def make_working_example_comparison():
    inputs = {
        'issue_description': 'New users are not receiving welcome emails after registration. The registration API returns 201 success but no email is sent. OrderService sends order confirmation emails correctly.',
        'error_text': '',
        'recent_changes': 'No recent changes to email infrastructure. Issue was discovered in production review — never worked since UserService was written 3 weeks ago.',
        'code_context': """class UserService:
    def __init__(self, db, email_service):
        self.db = db
        self.email_service = email_service

    def create_user(self, data: dict) -> User:
        user = User(**data)
        self.db.save(user)
        return user  # email_service never called""",
        'working_examples_text': """class OrderService:
    def __init__(self, db, email_service):
        self.db = db
        self.email_service = email_service

    def create_order(self, data: dict) -> Order:
        order = Order(**data)
        self.db.save(order)
        self.email_service.send(
            recipient=order.user.email,
            template='order_confirmation',
            context={'order': order}
        )
        return order""",
        'fix_attempts_count': 0,
    }
    return inputs, 'working_example_comparison', 'Pattern analysis case with working examples (C3 reference comparison): UserService fails to send welcome email but OrderService sends confirmation emails correctly — pipeline should identify missing email_service call as root cause by comparing the two implementations'
