"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="positive_missing_authz"."""


def make_positive_missing_authz():
    inputs = {
        'diff': """diff --git a/api/admin_actions.py b/api/admin_actions.py
new file mode 100644
index 0000000..9f8e7d6
--- /dev/null
+++ b/api/admin_actions.py
@@ -0,0 +1,28 @@
+from django.http import JsonResponse
+from django.views import View
+from django.contrib.auth.decorators import login_required
+from django.utils.decorators import method_decorator
+from .models import Order, UserProfile
+
+@method_decorator(login_required, name='dispatch')
+class DeleteOrderView(View):
+    def post(self, request, order_id):
+        try:
+            order = Order.objects.get(id=order_id)
+            order.delete()
+            return JsonResponse({'status': 'deleted'})
+        except Order.DoesNotExist:
+            return JsonResponse({'error': 'not found'}, status=404)
+
+@method_decorator(login_required, name='dispatch')
+class UpdateUserProfileView(View):
+    def post(self, request, user_id):
+        data = request.POST
+        profile = UserProfile.objects.get(user_id=user_id)
+        profile.bio = data.get('bio', profile.bio)
+        profile.display_name = data.get('display_name', profile.display_name)
+        profile.save()
+        return JsonResponse({'status': 'updated', 'user_id': user_id})""",
    }
    return inputs, 'positive_missing_authz', 'Diff adds an admin action endpoint that checks authentication but not authorization — should detect Authorization/IDOR (High) in api/admin_actions.py'
